"""
Model Factory for ARCH-FL

Creates models dynamically from configuration files, making the architecture
adaptive and configurable for different datasets and use cases.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Dict, Any, Optional
import yaml
import os


class ModelFactory:
    """
    Factory class for creating PyTorch models from configuration.

    This enables adaptive architecture that can handle different input sizes
    and configurations without hard-coding specific models.
    """

    def __init__(self, config_path: Optional[str] = None):
        """Initialize model factory with optional configuration."""
        self.config = {}
        self._default_config_dir = "config/model"
        if config_path:
            self.load_config(config_path)

    def load_config(self, config_path: str) -> None:
        """Load model configuration from YAML file."""
        with open(config_path, 'r') as f:
            self.config = yaml.safe_load(f)
    
    def load_config_by_name(self, config_name: str) -> Dict[str, Any]:
        """
        Load configuration by name from default config directory.
        
        Args:
            config_name: Name of the configuration file (without .yaml extension)
            
        Returns:
            Dictionary with loaded configuration
        """
        config_file = f"{self._default_config_dir}/{config_name}.yaml"
        if not os.path.exists(config_file):
            raise FileNotFoundError(f"Configuration file not found: {config_file}")
            
        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)
        
        return config
    
    def create_model_from_dataset(self, dataset_name: str, input_shape: tuple) -> nn.Module:
        """
        Create a model optimized for a specific dataset.
        
        Args:
            dataset_name: Name of the dataset
            input_shape: Input tensor shape (C, H, W)
            
        Returns:
            PyTorch model instance optimized for the dataset
        """
        try:
            from src.data.analyzer import DatasetAnalyzer
            
            # Analyze dataset to get characteristics
            analyzer = DatasetAnalyzer(dataset_name=dataset_name)
            metadata = analyzer.analyze()
            
            # Get recommended configuration
            config = analyzer.get_recommended_architecture_config()
            
            # Create and return model
            return self.create_model(config, input_shape)
            
        except ImportError:
            # Fallback to using DatasetAnalyzer directly
            warnings.warn("Could not import DatasetAnalyzer, using fallback")
            return self.create_adaptive_model(dataset_name, input_shape)

    def create_model(self, config: Optional[Dict[str, Any]] = None,
                     input_shape: Optional[tuple] = None) -> nn.Module:
        """
        Create a model from configuration.

        Args:
            config: Model configuration (overrides self.config if provided)
            input_shape: Input tensor shape (C, H, W) for automatic architecture adaptation

        Returns:
            PyTorch model instance
        """
        # Use provided config or fallback to loaded config
        config = config or self.config
        if not config:
            raise ValueError("No model configuration provided")

        model_type = config.get('name', 'SimpleCNN')

        # Handle auto-generated models (they use ConfigurableCNN architecture)
        if model_type.startswith('AutoGenerated') or model_type == 'FallbackCNN':
            return self._create_configurable_cnn(config, input_shape)
        elif model_type == 'SimpleCNN':
            return self._create_simple_cnn(config, input_shape)
        elif model_type == 'ResNet18':
            return self._create_resnet18(config)
        elif model_type == 'ConfigurableCNN':
            return self._create_configurable_cnn(config, input_shape)
        else:
            raise ValueError(f"Unknown model type: {model_type}")

    def _create_simple_cnn(self, config: Dict[str, Any],
                           input_shape: Optional[tuple] = None) -> nn.Module:
        """Create SimpleCNN model."""
        from .architectures import SimpleCNN
        num_classes = config.get('num_classes', 2)
        return SimpleCNN(num_classes=num_classes)

    def _create_resnet18(self, config: Dict[str, Any]) -> nn.Module:
        """Create ResNet18 model with medical imaging modifications."""
        import torchvision.models as models

        # Load pretrained ResNet18 and modify for grayscale input
        model = models.resnet18(pretrained=config.get('pretrained', False))

        # Modify first convolutional layer for grayscale input
        first_conv = config.get('modifications', {}).get('first_conv', {})
        in_channels = first_conv.get('in_channels', 1)
        out_channels = first_conv.get('out_channels', 64)
        kernel_size = first_conv.get('kernel_size', 7)
        stride = first_conv.get('stride', 2)
        padding = first_conv.get('padding', 3)

        # Replace first conv layer
        model.conv1 = nn.Conv2d(
            in_channels, out_channels,
            kernel_size=kernel_size,
            stride=stride, padding=padding,
            bias=False
        )

        # Modify final fully connected layer
        num_classes = config.get('num_classes', 2)
        model.fc = nn.Linear(model.fc.in_features, num_classes)

        return model

    def _create_configurable_cnn(self, config: Dict[str, Any],
                                 input_shape: Optional[tuple] = None) -> nn.Module:
        """
        Create a configurable CNN that adapts to input shape.

        This is the key to making the architecture adaptive and configurable.
        """
        if input_shape is None:
            raise ValueError("Input shape required for ConfigurableCNN")

        arch_config = config.get('architecture', {})
        input_channels = arch_config.get('input_channels', 1)
        conv_layers_config = arch_config.get('conv_layers', [])
        fc_layers_config = arch_config.get('fc_layers', [])
        activation = arch_config.get('activation', 'ReLU')
        pooling = arch_config.get('pooling', 'MaxPool2d')
        pool_kernel = arch_config.get('pool_kernel', 2)

        # Create layers dynamically
        layers = []
        current_channels = input_channels
        current_height, current_width = input_shape[1], input_shape[2]

        # Add convolutional layers
        for i, conv_config in enumerate(conv_layers_config):
            out_channels = conv_config['out_channels']
            kernel_size = conv_config['kernel_size']
            stride = conv_config['stride']
            padding = conv_config['padding']

            # Add conv layer
            layers.append(nn.Conv2d(current_channels, out_channels,
                                    kernel_size, stride, padding))

            # Add activation
            if activation == 'ReLU':
                layers.append(nn.ReLU())
            elif activation == 'LeakyReLU':
                layers.append(nn.LeakyReLU(0.1))

            # Add pooling
            if pooling == 'MaxPool2d':
                layers.append(nn.MaxPool2d(pool_kernel))
            elif pooling == 'AvgPool2d':
                layers.append(nn.AvgPool2d(pool_kernel))

            # Update dimensions for next layer
            current_channels = out_channels
            current_height = (current_height + 2 * padding - kernel_size) // stride + 1
            current_height = current_height // pool_kernel
            current_width = (current_width + 2 * padding - kernel_size) // stride + 1
            current_width = current_width // pool_kernel

        # Calculate flattened size
        flattened_size = current_channels * current_height * current_width

        # Add flatten layer
        layers.append(nn.Flatten())

        # Add fully connected layers
        fc_input_size = flattened_size
        for i, fc_config in enumerate(fc_layers_config):
            out_features = fc_config['out_features']

            if i == 0:
                # First FC layer connects to flattened conv output
                layers.append(nn.Linear(fc_input_size, out_features))
            else:
                layers.append(nn.Linear(fc_layers_config[i - 1]['out_features'], out_features))

            # Add activation (except for final layer)
            if i < len(fc_layers_config) - 1:
                if activation == 'ReLU':
                    layers.append(nn.ReLU())
                elif activation == 'LeakyReLU':
                    layers.append(nn.LeakyReLU(0.1))

            # Add dropout
            dropout = arch_config.get('dropout', 0.5)
            if dropout > 0 and i < len(fc_layers_config) - 1:
                layers.append(nn.Dropout(dropout))

        return nn.Sequential(*layers)

    def create_adaptive_model(self, dataset_name: str,
                              input_shape: tuple) -> nn.Module:
        """
        Create a model that adapts to the specific dataset using DatasetAnalyzer.

        This implements the adaptive architecture vision from the project proposal.
        """
        try:
            from src.data.analyzer import DatasetAnalyzer
            
            # Use DatasetAnalyzer to get optimal configuration
            analyzer = DatasetAnalyzer(dataset_name=dataset_name)
            metadata = analyzer.analyze()
            
            # Get recommended configuration based on dataset analysis
            config = analyzer.get_recommended_architecture_config()
            
            # Create and return model
            return self.create_model(config, input_shape)
            
        except ImportError:
            # Fallback to hard-coded configs if DatasetAnalyzer not available
            warnings.warn("DatasetAnalyzer not available, using fallback configurations")
            return self._create_fallback_adaptive_model(dataset_name, input_shape)
    
    def _create_fallback_adaptive_model(self, dataset_name: str,
                                       input_shape: tuple) -> nn.Module:
        """Fallback method with hard-coded configurations."""
        # Define fallback configurations
        fallback_configs = {
            'pneumoniamnist': {
                'name': 'ConfigurableCNN',
                'num_classes': 2,
                'architecture': {
                    'input_channels': 1,
                    'conv_layers': [
                        {'out_channels': 32, 'kernel_size': 3, 'stride': 1, 'padding': 1},
                        {'out_channels': 64, 'kernel_size': 3, 'stride': 1, 'padding': 1}
                    ],
                    'fc_layers': [
                        {'out_features': 128},
                        {'out_features': 2}
                    ],
                    'activation': 'ReLU',
                    'pooling': 'MaxPool2d',
                    'pool_kernel': 2,
                    'dropout': 0.5
                }
            },
            'mimic_cxr': {
                'name': 'ConfigurableCNN',
                'num_classes': 2,
                'architecture': {
                    'input_channels': 1,
                    'conv_layers': [
                        {'out_channels': 32, 'kernel_size': 3, 'stride': 2, 'padding': 1},
                        {'out_channels': 64, 'kernel_size': 3, 'stride': 2, 'padding': 1},
                        {'out_channels': 128, 'kernel_size': 3, 'stride': 2, 'padding': 1}
                    ],
                    'fc_layers': [
                        {'out_features': 256},
                        {'out_features': 2}
                    ],
                    'activation': 'ReLU',
                    'pooling': 'MaxPool2d',
                    'pool_kernel': 2,
                    'dropout': 0.5
                }
            },
            'chexpert': {
                'name': 'ConfigurableCNN',
                'num_classes': 14,
                'architecture': {
                    'input_channels': 1,
                    'conv_layers': [
                        {'out_channels': 32, 'kernel_size': 3, 'stride': 2, 'padding': 1},
                        {'out_channels': 64, 'kernel_size': 3, 'stride': 2, 'padding': 1},
                        {'out_channels': 128, 'kernel_size': 3, 'stride': 2, 'padding': 1},
                        {'out_channels': 256, 'kernel_size': 3, 'stride': 2, 'padding': 1}
                    ],
                    'fc_layers': [
                        {'out_features': 512},
                        {'out_features': 14}
                    ],
                    'activation': 'ReLU',
                    'pooling': 'MaxPool2d',
                    'pool_kernel': 2,
                    'dropout': 0.5
                }
            }
        }
        
        # Get configuration for this dataset
        config = fallback_configs.get(dataset_name.lower(), fallback_configs['pneumoniamnist'])
        
        # Create and return model
        return self.create_model(config, input_shape)


def get_model_factory():
    """Get singleton instance of ModelFactory."""
    return ModelFactory()


# Test the factory
if __name__ == "main":
    print("🧪 Testing ModelFactory...")

    factory = ModelFactory()

    # Test with SimpleCNN config
    print("\n1. Testing SimpleCNN from config...")
    simple_config = {
        'name': 'SimpleCNN',
        'num_classes': 2
    }
    simple_model = factory.create_model(simple_config)
    print(f"✅ SimpleCNN created: {simple_model}")

    # Test with ResNet18 config
    print("\n2. Testing ResNet18 from config...")
    resnet_config = {
        'name': 'ResNet18',
        'num_classes': 2,
        'pretrained': False,
        'modifications': {
            'first_conv': {
                'in_channels': 1,
                'out_channels': 64,
                'kernel_size': 7,
                'stride': 2,
                'padding': 3
            }
        }
    }
    resnet_model = factory.create_model(resnet_config)
    print(f"✅ ResNet18 created: {resnet_model}")

    # Test with ConfigurableCNN (adaptive to input shape)
    print("\n3. Testing ConfigurableCNN (adaptive)...")
    configurable_config = {
        'name': 'ConfigurableCNN',
        'architecture': {
            'input_channels': 1,
            'conv_layers': [
                {'out_channels': 32, 'kernel_size': 3, 'stride': 2, 'padding': 1},
                {'out_channels': 64, 'kernel_size': 3, 'stride': 2, 'padding': 1},
                {'out_channels': 128, 'kernel_size': 3, 'stride': 2, 'padding': 1}
            ],
            'fc_layers': [
                {'out_features': 256},
                {'out_features': 2}
            ],
            'activation': 'ReLU',
            'pooling': 'MaxPool2d',
            'pool_kernel': 2,
            'dropout': 0.5
        }
    }

    # Test with different input shapes
    for input_shape in [(1, 28, 28), (1, 224, 224)]:
        model = factory.create_model(configurable_config, input_shape)
        test_input = torch.randn(1, *input_shape)
        try:
            output = model(test_input)
            print(f"✅ ConfigurableCNN with input {input_shape}: output {output.shape}")
        except Exception as e:
            print(f"❌ ConfigurableCNN with input {input_shape}: {e}")

    print("\n🎉 ModelFactory tests completed!")
